### ISSUE TITLE
Typo's

### ISSUE THREAD

**Issue by swillems** [jgriss/ReproducibleMSGuidelines#16]
Tab Headers: Support this Guid**e**line
ToC: Manual **C**uration

**Comment by ypriverol** [comment]
Updated in the following PR https://github.com/jgriss/ReproducibleMSGuidelines/pull/18

**Comment by viikiid** [comment]
- "The **p**rocessed data is deposited in a public repository"
- "The **q**uantitative information of is made available in the HUPO-PSI standard file format mzTab."
- Sometimes there is a period after the sentence, sometimes not
- "If the software is made publically available" - should rather be "publicly"
- "During the peptide identification step, the search engine use**s** a decoy database to statistically access the q**ua**lity of the peptide identifications"
- We **recommend** to mention the stategy use to gen**e**rate the decoy database in the main manuscript.
- "If the libraries are **publicly** available, the source, version (if available)**,** or date of download should be mentioned in the manuscript."
- "In this rule, **we recommend to report the software version in the main manuscript.**"
- "We recommend the use of Jupyter notebooks to **record share** a complete analysis workflow." - two verbs in this sentence
- "Any transformation of data (e.g.**,** log transformation)"
