### ISSUE TITLE
We need to review best way to include references in the description 

### ISSUE THREAD

**Issue by ypriverol** [jgriss/ReproducibleMSGuidelines#17]
We need to find a way to include in the text (Description) citations to relevant publications related with the **Rule**: I suggest the following structure: 

The following reference text [PMID: XXXXX]. In the viewer application, we can add the prefix of PubMed (https://www.ncbi.nlm.nih.gov/pubmed/).

**Comment by jgriss** [comment]
I am not sure that this will work. The text is currently parsed as markdown. Therefore using `[` and `]` might cause rendering issues.

I'd rather use markdown to reference a publication using:

[Name et al.](http://link-to-pubmed-entry or article)

**Comment by ypriverol** [comment]
Agree @jgriss . I will close this issue.
