### ISSUE TITLE
Linked pages through top-level tabs

### ISSUE THREAD

**Issue by swillems** [jgriss/ReproducibleMSGuidelines#19]
Linked pages through top-level tabs are somewhat arbitrary:

- Scope: pop-up
- Google / Support / EuBIC: new tab
- Contribute: page redirect

This could be more uniform or at least more transparent for improved user-friendliness

**Comment by mlocardpaulet** [comment]
Also, I think the link for "EuBIC" should be https://www.proteomics-academy.org/bioinformatics

**Comment by jgriss** [comment]
Hi guys,
I changed the EuBIC link and adapted the "contributing" part to open in a new tab. Does that make sense?

**Comment by mlocardpaulet** [comment]
Perfect. Thanks.
