### ISSUE TITLE
Guidelines 90: For metanalysis papers, the identifiers of all reanalyzed datasets are mentioned in the manuscript

### ISSUE THREAD

**Issue by mlocardpaulet** [jgriss/ReproducibleMSGuidelines#23]
There is a typo in the guideline title "metanalysis" should be "meta-analysis"

**Comment by mlocardpaulet** [comment]
OK, I see now that it is also "metanalysis" that is used in the text of the scope. Is this the correct spelling?

**Comment by jgriss** [comment]
No, you are correct, it should be "meta-analysis"
