### ISSUE TITLE
Guidelines 248: The method used to create a decoy database is specified

### ISSUE THREAD

**Issue by mlocardpaulet** [jgriss/ReproducibleMSGuidelines#29]
Several typos in the description. Here is the corrected text: 
"During the peptide identification step, the search engine uses a decoy database to statistically access the quality of the peptide identifications. Multiple methods are available to generate the decoy databases (e.g reverse, random, etc). We recommende to mention the strategy used to generate the decoy database in the main manuscript."

**Comment by ypriverol** [comment]
I think the best way to fix all of them is by making a PR. You can do it and we will review it and merge.

**Comment by mlocardpaulet** [comment]
OK. Can do. Thanks.
